### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by ramiro-caso** [iamantony/qtcsv#15]
I've Dowloaded and compiled qtcsv. It does so faultlessly. Then I copied libqtcsv.1.0.0.dylib in /opt/local/libexec/qt4/lib and made its corresponding symlinks; I did the same for the header files, I copied them to /opt/local/libexec/qt4/include/QtCSV. So far no problem. But when I tried to compile this code:

`#include <QList>`
`#include <QStringList>`
`#include <QDir>`
`#include <QDebug>`
`#include "QtCSV/stringdata.h"`
`#include "QtCSV/reader.h"`
`int main()`
`{`
`    QString filePath = QDir::currentPath() + "/mytest.csv";`
`   QList<QStringList> readData = QtCSV::Reader::readToList(filePath);`
`    for ( int i = 0; i < readData.size(); ++i )`
`    {`
`        qDebug() << readData.at(i).join(",");`
`    }`
`    return 0;`
`}`

I get the following result:

> /usr/bin/clang++ -c -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.11 -Wall -W -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED -I/opt/local+quartz/libexec/qt4/share/mkspecs/macx-g++ -I. -I. -I/opt/local+quartz/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local+quartz/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/opt/local+quartz/libexec/qt4/include -F/opt/local/libexec/qt4/Library/Frameworks -F/opt/local/libexec/qt4/lib -o main.o main.cpp
/usr/bin/clang++ -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.11 -o ejemplo-csv main.o   -F/opt/local/libexec/qt4/Library/Frameworks -F/opt/local/libexec/qt4/lib  -F/opt/local/libexec/qt4/Library/Frameworks -F/opt/local/libexec/qt4/lib -L/opt/local/libexec/qt4/lib -framework QtCore 
Undefined symbols for architecture x86_64:
  "QtCSV::Reader::readToList(QString const&, QString const&, QString const&, QTextCodec*)", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ejemplo-csv] Error 1

In a forum I read something about these errors happen when linking against libc and not against libstdc, so i modified the qtcsv Makefile adding to LFLAGS "-stdlib=stdlibc++". In order to checkout if it linked as desired I ran:
`otool -L libqtcsv.1.0.0.dylib`
and the output was:
>libqtcsv.1.0.0.dylib:
	/usr/lib/libqtcsv.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/libexec/qt4/Library/Frameworks/QtCore.framework/Versions/4/QtCore (compatibility version 4.8.0, current version 4.8.7)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

So this time I was sure it linked against libstdc++. But when I try to compile the program with this library I got the same error. 

Can you help please?

Im Using Os X El Capitan 10.11.2
MacPorts 2.3.4
qt4-mac 4.8.7_4
Xcode  7.1 (7B91b)

**Comment by iamantony** [comment]
Well, it seems that linker failed to find qtcsv library in your system.

Maybe you should explicitly specify what library you want to link? See this answer: http://stackoverflow.com/questions/32425361/ld-symbols-not-found-for-architecture-x86-64-clang-linker-command-failed

Another solution - try to build this example project: https://github.com/iamantony/qtcsv-example
