### ISSUE TITLE
extra linefeed

### ISSUE THREAD

**Issue by ritskes** [iamantony/qtcsv#16]
We have different results in notepad, notepad++ and wps
![image](https://cloud.githubusercontent.com/assets/19264042/15110340/903c0410-15e0-11e6-9d1b-5af6371eafe1.png)

Actually we just took an original CSV and removed some fields and wrote it back using your CSV program. But the original file looks way different then the CSV made by your LIB.
Looks like there is an extra linefeed.

What we did is:

void MainWindow::on_PB_Start_clicked()
{

    QString dir;
    if(ui->spinBoxProvider->value()==1)
    {
        dir = "C:/Users/Ritsk/Documents/QT PROJECTS/TarievenProgramma/CSV/DIDLOGIC";
    }
    else
    {
        dir = "C:/Users/Ritsk/Documents/QT PROJECTS/TarievenProgramma/CSV/COMMPEAK";
    }

    QDir directory(dir);
    const QString FS = QFileDialog::getOpenFileName(this,tr("Open File"), directory.absolutePath(), tr("Files (*.csv)"));
    QList<QStringList> data = QtCSV::Reader::readToList(FS);
    data.removeAt(0);
    for(int i=1;i<data.size();i++)
    {
        if(ui->spinBoxProvider->value()==1)
        {
            data[i].removeAt(0);
        }
        else
        {
            data[i].removeAt(0);
            data[i].removeAt(2);
        }
    }
    QtCSV::StringData strData;
    QStringList Header;
    Header << "RATE" << "PREFIX";
    strData.addRow(Header);
    for(int i=1;i<data.size();i++)
    {
        QStringList strList;
        if(ui->spinBoxProvider->value()==1)
        {
            strList << data[i].at(0) << data[i].at(1);
        }
        else
        {
            //QString s = data[i].at(0);
            //s + "\r";
            strList << data[i].at(1) << data[i].at(0);
        }
        strData.addRow(strList);
    }

    bool writeResult;
    if(ui->spinBoxProvider->value()==1)
    {
        writeResult = QtCSV::Writer::write("C:/Users/Ritsk/Documents/QT PROJECTS/TarievenProgramma/DIDLOGIC.csv", strData);

    }
    else
    {
        writeResult = QtCSV::Writer::write("C:/Users/Ritsk/Documents/QT PROJECTS/TarievenProgramma/COMMPEAK.csv", strData);
    }

    if(writeResult)
    {
        QMessageBox msgBox;
        msgBox.setText("CSV has been CONVERTED");
        msgBox.exec();
    }
    else
    {
        QMessageBox msgBox;
        msgBox.setText("ERROR: CSV has NOT been CONVERTED!!");
        msgBox.exec();
    }

I have send the code to your email adres as well.

WHAT are we doing WRONG?
Why is the original different then the one made with your LIB?

**Comment by iamantony** [comment]
Quite interesting. It seems that problem is really in a extra line feed. Could you send me your original csv-file (or part of it) so I could use it for testing?

**Comment by iamantony** [comment]
Bug is fixed: 7c34e32d0f0f0990f19c05f757be18af9fdea88f
