### ISSUE TITLE
Error parsing quatted strings

### ISSUE THREAD

**Issue by mehrafsa** [iamantony/qtcsv#17]
The cell value of

> CCLK="yy/MM/dd,hh:mm:ss±zz"

 should be stored like 

> "CCLK=""yy/MM/dd,hh:mm:ss±zz"""

 in a csv raw text, but it seems the reader could not parse the above format correctly.

**Comment by Spaghetti-Cat** [comment]
Is it correct that there are only 2 quotes before "yy". Shouldn't there be 3?

**Comment by iamantony** [comment]
@mehrafsa thanks for information.

String `CCLK="yy/MM/dd,hh:mm:ss±zz"` should be written in file as `"CCLK=""yy/MM/dd,hh:mm:ss±zz"""`. No error here, @Spaghetti-Cat .

I recently checked the Reader class and find out that Reader can parse this string correctly (and put it in one cell) in this cases:
* string `"CCLK=""yy/MM/dd,hh:mm:ss±zz"""` is the only string in the row
* string `"CCLK=""yy/MM/dd,hh:mm:ss±zz"""` is the last element in the row

But if we have _raw_ row like this:
`"CCLK=""yy/MM/dd,hh:mm:ss±zz""","one, two"`

then Reader will fail to parse this row correctly.

So yep we have a bug here. It seems that Reader needs more robust parse algorithm.

Unfortunately I don't have much time now to fix it, so forks are welcome!

**Comment by mehrafsa** [comment]
@iamantony  thanks, you have done decent work, I actually corrected that little mistake in my own code. Only I think it was such little mistake to fork your code. I will share my solution but if you think I should fork it, tell me.
solution: you only need to keep track of `"` when you face them, they should count to an even number. let's say you define a boolean variable called q with initial value of false when you face a `"` toggle the value. the whole field is parsed if and only if q is false and you face a comma. (just this will solve the problem)
you can add error checking issues for your code as follows:
single occurrence of `"` are permitted only at the begging and end of a field. otherwise they should be in pairs. that is all and your code is prefect.

**Comment by iamantony** [comment]
@mehrafsa many thanks for your solution!
If think it would be great if you will be able to find time to make a fork of the project, make the necessary changes and create pull request. I think it would be fair, because it is your code/solution and your contribution to the project.

**Comment by iamantony** [comment]
Issue fixed in commit 08fb30a22fda38ccdfb4acd5db9dfea7fecdeb48
