### ISSUE TITLE
Unable to read CSV files with filename containing dots "."

### ISSUE THREAD

**Issue by filipaog** [iamantony/qtcsv#18]
Hi,
I found that QtCSV lib cannot read files which have in its filename string  one or more dots.

The file src\sources\filechecker.h calls the `completeSuffix()` function of `QInfoFile `class to check the file extension.

Line 15 to 24:
```
    inline bool CheckFile(const QString& filePath)
    {
        QFileInfo fileInfo(filePath);

        if ( fileInfo.isAbsolute() && "csv" == fileInfo.completeSuffix() )
        {
            return true;
        }

        return false;
    }
```
As you can see in [Qt documentation](http://doc.qt.io/qt-4.8/qfileinfo.html#completeSuffix) the `completeSuffix()` function returns all characters in the file after (but not including) the first dot ".". In case you have a filename such as "myFile.v123.csv" the return string will be "v123.cvs" which is not equal to "cvs as supposed in line 17 of filechecker.h.

I replaced `completeSuffix()` by `suffix()` and everything worked just fine. I checked and the `CheckFile` function is used file validation in both read and write features.

Please let me know if there's any additional implication on changing this in the library.

Best,
Filipe

**Comment by iamantony** [comment]
Thank you for this issue! You are right, this is a bug (and my oversight). Your solution works perfectly. See commit adf07ce4ee7903fcbadf97ff4d041e87a3645685.
