### ISSUE TITLE
Build issues under Windows

### ISSUE THREAD

**Issue by pbek** [iamantony/qtcsv#22]
Thanks a lot for this nifty library!

I use it in <https://github.com/pbek/QOwnNotes> and it works great under Linux und macOS.
But when I build QOwnNotes under Windows with AppVeyor (and also locally) I get the error message:
`/release/tabledialog.o:tabledialog.cpp:(.text+0x68d): undefined reference to _imp___ZN5QtCSV6Reader10readToListERK7QStringS3_S3_P10QTextCodec`

for example here: <https://ci.appveyor.com/project/pbek/qownnotes/build/windows-b2567>

`tabledialog.cpp` is where I use your library at <https://github.com/pbek/QOwnNotes/blob/develop/src/dialogs/tabledialog.cpp#L70>

Do you have any idea why this might happen?

This is the AppVeyor config: <https://github.com/pbek/QOwnNotes/blob/develop/appveyor.yml>
And this my qmake project file: <https://github.com/pbek/QOwnNotes/blob/develop/src/QOwnNotes.pro>

Thank you very much!

**Comment by pbek** [comment]
I now realized that I got the error because under Windows a DLL will be generated and that DLL wasn't found.

**Comment by iamantony** [comment]
By default DLL will be saved to the main folder ($PWD) of the library. See *DESTDIR* parameter in *qtcsv.pro*

**Comment by pbek** [comment]
Thank you.
