### ISSUE TITLE
Hi, please help. 

### ISSUE THREAD

**Issue by JayJoeSeventh** [iamantony/qtcsv#24]
Hi,

I am getting error while compiling your QtCSV. The problem arises due to the no-longer presence of .addRowValues(). By only changing it to addRow(), I am getting a list of errors.

Please help.

Thank you

JayJoe

**Comment by iamantony** [comment]
Hi! Which version (or commit number) of qtcsv do you use? Could you provide build log?
Also see code of [qtcsv-example](https://github.com/iamantony/qtcsv-example) project. Maybe it would help.

**Comment by JayJoeSeventh** [comment]
Hi, thanks for willing to reply, thank you.

I am using Qt 5.7.1. The error I am receiving is main.cpp:24: error: 'class QtCSV::StringData' has no member named 'addRowValues'
     strData.addRowValues(strList);
             ^
I have tried the example as well, same error I get. And I read your stringdata.h, the header file does not contains addRowValues() function. 

If I use addRow() function, I am getting these error 
![image](https://cloud.githubusercontent.com/assets/25404500/22461741/6e66e0a8-e7e5-11e6-9803-724293db4497.png)

Please help, need it for my project :( Thank you

**Comment by iamantony** [comment]
Yes, StringData do not have method addRowValues(). Instead you should use addRow().
About errors that you get. It seems that linker can't find library file (*libqtcsv.so* if you use Linux).

**Comment by iamantony** [comment]
In file [example.pro](https://github.com/iamantony/qtcsv-example/blob/master/example/example.pro):

``` qmake
unix|win32: LIBS += -L$$PWD/../qtcsv/ -lqtcsv
INCLUDEPATH += $$PWD/../qtcsv/include
```

These lines tells to liker where:
1. it could find library file
2. it could find headers of the library
