### ISSUE TITLE
Not all field are parsed in an csv file.

### ISSUE THREAD

**Issue by JacekMarcinJ** [iamantony/qtcsv#29]
Hello!

I have big csv file: I have 31 headers and 31 fields in each row below headers. Bug is in first row of my table:
Headers:
"cNumer","Data","NazwaS","Szablon","MagDest","MagW","MagP1","MagP2","RRuch","Zlec","CreUser_","CreTime","ModUser_","ModTime","DataOC","NumerFakt","Opis","SumWart","SumWartW","id_transp","PrzewNs","CzyOpakZ","opakdo","DokMId1","DokMId2","KontrId1","KontrId2","cLista_DokH","_checked","przewoznikKontrId1","przewoznikKontrId2"

First row:
"PR/3/15","2015-07-22 14:17:53.650","IKEA-125-STO","_WZ","(brak)","OCI��","Kntr_IKEA125STO","(brak)","OCIAZ",,"i.kret","2015-07-22 14:17:53.650","i.kret","2015-07-22 14:19:29.402",,,"",,,"","","NIE",0,1,1586989,1,7090,"",0,,

You will notice that last two fields are empty. But QtCsv threats them as one! I have serious errors in my program just because this bug! Please fix this as soon as possible.

thanks and best regards
Jacek

**Comment by JacekMarcinJ** [comment]
Is it very difficult fix this typo?!?

**Comment by iamantony** [comment]
Hi. Sorry for no response. 
I think I have found an error. Today I will test my solution and all went good, tomorrow you will see changes in master branch.

**Comment by iamantony** [comment]
@JacekMarcinJ please test qtcsv with latest commit in master branch

**Comment by JacekMarcinJ** [comment]
Now it works! Thanks!

**Comment by iamantony** [comment]
Thank you for this bug)
