### ISSUE TITLE
addRowValues method does not exist

### ISSUE THREAD

**Issue by mmolero** [iamantony/qtcsv#32]
Hi  Antony

First it all, thanks for sharing.

FYI (my 2 cents)
I've seen that in the example included in the **README.md** you mentioned the use of a method, **addRowValues** for the Class **StringData**. However, this class method does not exist in the current commit. But there is an addRow Method (without the Suffix **Values**). 
Thanks!!!

**Comment by iamantony** [comment]
Hi @mmolero !
Thank you for this info :+1: ! Fixed in d1d50342f2d00f5ad4501807043518560bf161b4 :-):
