### ISSUE TITLE
Failure when line begins with closing field delimiter

### ISSUE THREAD

**Issue by davidljung** [iamantony/qtcsv#37]
Thanks for QtCSV!

I am reading some CSV files from elsewhere that I have no control over.  I've discovered that some rows span multiple lines of the file and are delimited by double quotes (the default). However, with lines on which the terminating quote is at the first position of the line, QtCSV doesn't interpret it correctly and adds the quote to the field data and gets confused.

For example, consider some rows like:

    A,B,C,D
    a,b,c,d
    a,"b field","c field
    ","d field"
    aa,bb,cc,dd

QtCSV returns the 3rd row as "a", "b field", "c field\n\\"\,\\"d field", ""

I hacked a fix for my immediate purpose by adding a line in reader.cpp to check if the line starts with '\\"' and if so, just add a leading " " (space).
However, I thought you would like to fix it in the master properly.

(Note that it would be useful if the reader method could take a string or stream instead of just a filename.  That way, I could have read the (small) file into memory first and done a search-replace before passing it to QtCSV).

Cheers,
David

**Comment by iamantony** [comment]
Hi @davidljung !

Thanks for the bug! I used your example input and library (on current master) parce 3rd row like this:

    "a", "b field", "c field\n,d field"

This line is different from what you have provided - no additional empty field on the end of the row (""). That is strange. Maybe I misunderstood you. But anyway there is a bug in Reader. I tried to fix it in dev branch. Could you test latest code on dev branch with your input files?

Nice idea about new reader methods. I'll try to implement it.

**Comment by davidljung** [comment]
Great - yes, I did a quick test of the dev branch and it appears to read my CSV files correctly.  Thanks!

**Comment by iamantony** [comment]
Fixed in 71f34dbafa8b2c47fcf875522da8cbd637a0c1e0
