### ISSUE TITLE
Reader: Line breaks lost

### ISSUE THREAD

**Issue by roundcubes** [iamantony/qtcsv#41]
Hello,

we noticed that when the CSV is read, the line breaks that have been lost are lost. These do not seem to be imported.

**Comment by iamantony** [comment]
Hi!

Could you provide an example? I did not quite understand what you mean...

**Comment by roundcubes** [comment]
Hello, I have tested a bit and found the following.
If there are only returns in a text, \r, they are not imported.

Example:

Column1, Column2; Column3
"Hello with\rHello again"; "Hello Col 3"

If i replace all \r with \n or \r\n, it works.

If i look the exported file with Numbers or Excel, it seems with only \r correct.

**Comment by iamantony** [comment]
Hi @roundcubes !
Please test qtcsv from dev branch with your files. I hope the latest commits fixed the issue.

**Comment by roundcubes** [comment]
Hello,

Excuse the long absence. The solution works. Many Thanks
