### ISSUE TITLE
Add more methods to operate on `QIODevice` instead of the filepath

### ISSUE THREAD

**Issue by apollo13** [iamantony/qtcsv#43]
To be able to reuse the library in more contexts it would be nice if in addition to `filepath` an overload for `QIODevice` would exist. This would allow writing/reading the data into a buffer. Would you be open to such an addition?

**Comment by iamantony** [comment]
Yeah, nice idea =)

**Comment by apollo13** [comment]
I do not know how much this library is used, would it have to be an addition for now or could we just replace it and do it as backwards incompatible change?

**Comment by iamantony** [comment]
Let's be more user-friendly and start with addition of new functions.

**Comment by iamantony** [comment]
@apollo13 nice work!
