### ISSUE TITLE
Is QtCsv compile able for Android?

### ISSUE THREAD

**Issue by SzykCech** [iamantony/qtcsv#48]
Is QtCsv compile able for Android?
I failed with some older version (from 2017-06-13):
`19:52:55: Uruchamianie kroków budowania dla projektu qtcsv...
19:52:55: Konfiguracja niezmieniona, krok qmake pominięty.
19:52:55: Uruchamianie "C:\x-tools\Qt\Tools\mingw530_32\bin\mingw32-make.exe" 
C:\x-tools\android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -c -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove --sysroot=C:\x-tools\android-ndk-r15c/platforms/android-16/arch-arm/ -O2 -Os -mthumb -std=gnu++11 -Wall -W -Werror -Wformat=2 -Wuninitialized -Winit-self -Wswitch-enum -Wundef -Wpointer-arith -Wdisabled-optimization -Wcast-align -Wcast-qual -D_REENTRANT -fPIC -DQTCSV_LIBRARY -DQT_NO_DEBUG -DQT_CORE_LIB -I../QtCSV -I. -I../QtCSV/include -I../../../x-tools/Qt/5.9.1/android_armv7/include -I../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore -I. -I../../../x-tools/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/include -I../../../x-tools/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -I../../../x-tools/android-ndk-r15c/platforms/android-16/arch-arm/usr/include -I../../../x-tools/Qt/5.9.1/android_armv7/mkspecs/android-g++ -o writer.obj ../QtCSV/sources/writer.cpp
In file included from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:47:0,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlocale.h:43,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qtextstream.h:46,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/QTextStream:1,
                 from ../QtCSV/sources/writer.cpp:7:
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qmap.h: In instantiation of 'QMapData<Key, T>::Node* QMapData<Key, T>::end() [with Key = QString; T = QVariant; QMapData<Key, T>::Node = QMapNode<QString, QVariant>]':
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qmap.h:793:22:   required from 'QMap<K, V>::iterator QMap<K, V>::insertMulti(const Key&, const T&) [with Key = QString; T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:798:66:   required from here
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qmap.h:215:58: error: cast from 'QMapNodeBase*' to 'QMapData<QString, QVariant>::Node* {aka QMapNode<QString, QVariant>*}' increases required alignment of target type [-Werror=cast-align]
     Node *end() { return reinterpret_cast<Node *>(&header); }
                                                          ^
In file included from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qstringlist.h:41:0,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/QStringList:1,
                 from ../QtCSV/include/qtcsv/writer.h:5,
                 from ../QtCSV/sources/writer.cpp:1:
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h: In instantiation of 'void QList<T>::node_destruct(QList<T>::Node*, QList<T>::Node*) [with T = QVariant]':
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:866:68:   required from 'void QList<T>::dealloc(QListData::Data*) [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:827:18:   required from 'QList<T>::~QList() [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:762:30:   required from here
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:496:34: error: cast from 'QList<QVariant>::Node*' to 'QVariant*' increases required alignment of target type [-Werror=cast-align]
         while (from != to) --to, reinterpret_cast<T*>(to)->~T();
                                  ^
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h: In instantiation of 'void QList<T>::node_copy(QList<T>::Node*, QList<T>::Node*, QList<T>::Node*) [with T = QVariant]':
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:788:92:   required from 'void QList<T>::detach_helper(int) [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:572:32:   required from 'void QList<T>::reserve(int) [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:763:38:   required from here
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:475:17: error: cast from 'QList<QVariant>::Node*' to 'QVariant*' increases required alignment of target type [-Werror=cast-align]
                 new (current) T(*reinterpret_cast<T*>(src));
                 ^
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:481:17: error: cast from 'QList<QVariant>::Node*' to 'QVariant*' increases required alignment of target type [-Werror=cast-align]
                 (reinterpret_cast<T*>(current))->~T();
                 ^
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h: In instantiation of 'void QList<T>::node_destruct(QList<T>::Node*) [with T = QVariant]':
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:604:36:   required from 'void QList<T>::append(const T&) [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:386:15:   required from 'QList<T>& QList<T>::operator<<(const T&) [with T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:765:27:   required from here
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qlist.h:452:39: error: cast from 'QList<QVariant>::Node*' to 'QVariant*' increases required alignment of target type [-Werror=cast-align]
     else if (QTypeInfo<T>::isComplex) reinterpret_cast<T*>(n)->~T();
                                       ^
In file included from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qshareddata.h:46:0,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qfileinfo.h:45,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qdir.h:44,
                 from ../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/QDir:1,
                 from ../QtCSV/sources/writer.cpp:6:
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qhash.h: In instantiation of 'static QHash<K, V>::Node* QHash<K, V>::concrete(QHashData::Node*) [with Key = QString; T = QVariant; QHash<K, V>::Node = QHashNode<QString, QVariant>]':
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qhash.h:536:18:   required from 'static void QHash<K, V>::deleteNode2(QHashData::Node*) [with Key = QString; T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qhash.h:576:5:   required from 'void QHash<K, V>::freeData(QHashData*) [with Key = QString; T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qhash.h:254:47:   required from 'QHash<K, V>::~QHash() [with Key = QString; T = QVariant]'
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qvariant.h:779:30:   required from here
../../../x-tools/Qt/5.9.1/android_armv7/include/QtCore/qhash.h:237:45: error: cast from 'QHashData::Node*' to 'QHash<QString, QVariant>::Node* {aka QHashNode<QString, QVariant>*}' increases required alignment of target type [-Werror=cast-align]
         return reinterpret_cast<Node *>(node);
                                             ^
cc1plus.exe: all warnings being treated as errors
Makefile:869: recipe for target 'writer.obj' failed
mingw32-make: *** [writer.obj] Error 1
19:52:58: Proces "C:\x-tools\Qt\Tools\mingw530_32\bin\mingw32-make.exe" zakończył się kodem wyjściowym 2.
Błąd budowania / instalowania projektu qtcsv (zestaw narzędzi: Android dla armeabi-v7a (GCC 4.9, Qt 5.9.1 for Android armv7))
Podczas wykonywania kroku "Make"
19:52:58: Czas trwania: 00:03.`

**Comment by iamantony** [comment]
Hello @SzykCech !

Sorry for a late reply. I did not try to compile qtcsv for Android so there could be errors. I will try to setup environment for Qt and Android and check errors

**Comment by SzykCech** [comment]
Any news in this area?!?

**Comment by iamantony** [comment]
Well, no(
Unfortunately I do not have much free time, so I will appreciate any help with this issue!

**Comment by SzykCech** [comment]
In true probably this is not QtCsv bug. I think this, because problem is with memory address alignment in templates included from files: qhash.h, qlist.h, qmap.h all from QtCore. It seems it works on x86/x64 due to less restricted memory alignment policy (which can be violate and only will impact with performance hurt, but still works). This is no option for ARM processors - memory alignment is mandatory/compulsory.
The broken code is partly not understandable to me. For example (C:\x-tools\Qt\5.9.2\android_armv7\include\QtCore\qlist.h:496):
`while (from != to) --to, reinterpret_cast<T*>(to)->~T();`
Why they use comma after --to?!? What does it mean such code?!?
And why they use explicit destructor call?!? Why they don't use `delete` operator?!?

**Comment by albertino80** [comment]
I compiled and tested this lib with Qt 5.14.2 on Android arm. No problems.

**Comment by iamantony** [comment]
@albertino80 thanks! Does qtcsv need any special changes to be compilable on Android?

**Comment by albertino80** [comment]
No changes, the master version works.

**Comment by iamantony** [comment]
Thanks, closing the issue.
