### ISSUE TITLE
Can you added a "lineno" parameter to the methods of AbstractProcessor?

### ISSUE THREAD

**Issue by YanZhikai** [iamantony/qtcsv#50]
Hi, everybody:
    I am a new guy enrolled in github recently.
    I found AbstractProcessor is useful, and I think it could be better if there is a **lineno** (number of the line in csv being processed currently) parameter in the methods of AbstractProcessor. With an added 'lineno' parameter , the users can locate errors or exceptions in csv rapidly.
     Hoping to get any feedback. Thanks a lot!

**Comment by iamantony** [comment]
Hi, @YanZhikai !

Nice idea, but I think not everybody will need such information. Also it is not so hard to implement such functionality:


``` cpp
class CountingProcessor : public Reader::AbstractProcessor {
public:
    QList<QStringList> data;

    CountingProcessor() : m_lineCounter(0) { }
    virtual ~CountingProcessor() { }
    virtual void preProcessRawLine(QString& /*line*/) {
        ++m_lineCounter;
    }

    virtual bool processRowElements(const QStringList& elements) {
        if (DoSomething(elements)) {
            data << elements;
            return true;
        }
        
        qDebug() << __FUNCTION__ << "Something went wrong on line" << m_lineCounter;
        return false;
    }

private:
    size_t m_lineCounter;
};
```

**Comment by YanZhikai** [comment]
Thank you very much! I got it :)
